### ISSUE TITLE
포스팅 잘 봤습니다! 덕분에 jwt인증구현에 많은 도움이 되었습니다

### ISSUE THREAD

**Issue by mincheolsong** [5xJIN/react-pactice#1]
포스팅 잘 봤습니다! 덕분에 jwt인증 공부에 많은 도움이 되었습니다  
그런데 궁금한점이 생겨 issue탭에 질문을 남깁니다.
`./auth/CheckToken.js`에서

```js
useEffect(()=>{
   토큰 확인하는 코드
}
,[refreshToken, dispatch, key])
```
과 같이 useEffect를 사용하는 이유가 무엇인가요?  
refreshToken이 변경된 경우와, 현재 window의 위치가 변경된 경우에만 함수를 실행하기 위해서 사용하는 것인가요?  
그렇다면 dispatch는 어떤이유로 넣은 것인가요?
감사합니다...!

```js
export function CheckToken(key) {
    const [isAuth, setIsAuth] = useState('Loaded');
    const { authenticated, expireTime } = useSelector(state => state.token);
    const refreshToken = getCookieToken();
    const dispatch = useDispatch();

    useEffect(()=> {
        const checkAuthToken = async () => {
            if (refreshToken===undefined) {
                dispatch(DELETE_TOKEN());
                setIsAuth('Failed');
            } else {
                if (authenticated && new Date().getTime() < expireTime){
                    setIsAuth('Success');
                } else {
                    const response = await requestToken(refreshToken);

                    if (response.status) {
                        const token = response.json.access_token;
                        dispatch(SET_TOKEN(token));
                        setIsAuth('Success');
                    } else {
                        dispatch(DELETE_TOKEN());
                        removeCookieToken();
                        setIsAuth('Failed');
                    }
                }
            }
        };
        checkAuthToken();
    }, [refreshToken, dispatch, key]);

    return {
        isAuth
    };
}
```

**Comment by 5xJIN** [comment]
@mincheolsong 
도움이 되셨다니 다행입니다. 😄 

위와 같이 `useEffect` 를 사용한 이유는 deps안의 값이 변경될 때마다 쿠키에 저장된 refresh token의 유무와 redux에 저장된 access token 유효성을 검증하기 위함입니다.
이때 생각해야 할 점은 `웹 브라우저를 새로고침 할 때마다 redux 에 저장된 모든 값들은 initialState 로 초기화된다` 는 점입니다. 즉, 라우터 이동 시 뿐만 아니라 웹 브라우저의 새로고침 수행을 감지하여 token 검증을 수행하여야 합니다.

- `refreshToken`의 경우 cookie 에 저장되어 있기 때문에 웹 브라우저의 새로고침이 수행되더라도 여전히 같은 값을 유지할 것입니다. 따라서 해당 페이지에 접근하는 유저가 인증된(로그인 된) 유저인지를 판별하기 위한 값으로 `로그인/로그아웃` 을 수행했을 때에만 해당 useEffect가 실행될 것입니다.
- `dispatch`의 경우 `accessToken`을 redux에 저장하기 위한 useDispatch hook입니다. 궁금하셨을 점은 왜 useEffect hook의 deps에 선언되었을까로 추측됩니다. dispatch는 useDispatch hook을 사용하기 위해 선언한 변수로 계속 같은 값을 유지할 것입니다. 따라서 `앱이 최초 랜더링(새로고침 제외)`되었을 때에만 해당 useEffect 가 실행됩니다. 초기에 해당 토큰 검증을 수행하기 위해 선언하였다고 생각하시는 게 좋겠습니다.
- `key` 의 경우 useLocation hook 으로부터 return 받은 location 객체의 일부입니다. 이해를 돕기 위해 useLocation hook 에 대한 독스 링크를 첨부하겠습니다. ([https://reactrouter.com/docs/en/v6/hooks/use-location](https://reactrouter.com/docs/en/v6/hooks/use-location)) 간략히 말하자면 location 객체 고유의 식별자로 클릭으로 인한 링크 이동 또는 새로고침 시에도 값이 변하게 됩니다. 즉, 링크 이동(router 이동) 뿐만 아니라 웹 브라우저의 새로고침 시에도 token 검증을 수행하기 위해 선언하였습니다.
